apiVersion: apps/v1
kind: Deployment
metadata:
  name: computers-deployment
  labels:
    app: computers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: computers
  template:
    metadata:
      labels:
        app: computers
    spec:
      containers:
      - name: computers
        image: 165317185480.dkr.ecr.us-east-1.amazonaws.com/shopping-site-computers:342a70b2d7e4f735e725a1203469194ea53a076b
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: computers-service
  labels:
    app: computers
spec:
  type: ClusterIP
  selector:
    app: computers
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
